image: ruby:3.3-alpine

default:
  before_script:
    - apk add -U build-base
    - bundle install -j $(nproc)

rubocop:
  stage: test
  script:
    - rubocop --fail-level W

rspec:
  stage: test
  variables:
    COVERAGE: cobertura
  script:
    - apk add -U emacs-nox ncurses
    - rspec
  coverage: '/LOC \(\d+\.\d+\%\) covered/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
