---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: no

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*
    - lib/tasks/*
    - fronde.gemspec

Metrics/ClassLength:
  CountAsOne:
    - hash
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - hash
    - method_call

Metrics/ModuleLength:
  Max: 120

RSpec:
  Severity: warning

RSpec/ExampleLength:
  Max: 14
  CountAsOne:
    - hash
    - heredoc
    - method_call

Style:
  Severity: warning

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/PreferredHashMethods:
  EnforcedStyle: verbose
