---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

require:
- rubocop-performance
- rubocop-rspec

Layout:
  Severity: warning

Layout/EmptyLineAfterGuardClause:
  Enabled: no

Layout/LineLength:
  Max: 80
  Exclude:
  - spec/**/*

Metrics:
  Severity: warning

Metrics/AbcSize:
  Enabled: no

Metrics/BlockLength:
  Max: 30
  Exclude:
  - spec/**/*
  - lib/tasks/*
  - fronde.gemspec

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 120
  Exclude:
  - lib/fronde/config/lisp_config.rb
  - lib/fronde/utils.rb

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

RSpec/ExampleLength:
  Enabled: no

RSpec/MultipleExpectations:
  Enabled: no

RSpec/NestedGroups:
  Max: 4

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: yes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
