#+title: News from Fronde
#+language: en

* Nov. 2023 - v0.4 release

This new release brings a lot of stability improvements and inner
refactoring. Even if the visible changes list might look a bit poor,
this release is a big step forward and will help a lot to develop new
features in the future. Some parts of the software were poorly designed
and we worked hard to improve the coding.

#+begin_noteblock
After the update, you will need to update your installations and force a
full publication of your websites (because the way templates are
inserted inside published files changed). Actually, this will become
the new standard routine after any fronde upgrade.

#+begin_src shell
  fronde update
  fronde build -f
#+end_src
#+end_noteblock

Here is the list of the most visible changes:

- Improve Gemini support
- Translate all console messages
- Introduce a new onboarding command (~new~ instead of ~init~) to follow
  other static website generator habbits
- Rework tags and Atom feeds publication
  + Output full article body in Atom feeds
  + Announce each Atom feed in its related tag page
  + Move tag pages and Atom feeds /inside/ the related blog source. They
    are not shared anymore but specific to their source.

#+begin_warningblock
As tags and feeds are now published under their related source public
path and no more directly at the root of the publication folder, you
might want to setup some redirections in your web server configuration.

For the following example configuration:

#+begin_src yaml
  ---
  sources:
  - path: src/news
    is_blog: true
#+end_src

Feeds and tags will now be published under ~public_html/news/feeds/~ and
~public_html/news/tags/~ instead of ~public_html/feeds/~ and
~public_html/tags/~. Thus you might want to setup some redirections like
the following for nginx:

#+begin_src
  location ~ ^/tags/(?<slug>.*)$ {
      return 301 /news/tags/$slug;
  }
  location ~ ^/feeds/(?<slug>.*)$ {
      return 301 /news/feeds/$slug;
  }
#+end_src
#+end_warningblock
