#+title: Neruda
#+author: Étienne Deparis
#+lang: en
#+keywords: static website generator, ruby, gem, org mode, emacs
#+description: Neruda is a ruby gem, which helps you to manage your
#+description: static website generated with Org mode

* What's for?

#+attr_html: :style width:150px;float:right;margin-top:-4.5em;margin-left:2em;
[[file:themes/default/img/Firma_Pablo_Neruda.svg]]

Neruda is a static website generator made for [[https://orgmode.org][Org files]]. It improves the
default Org HTML exporting/publishing routine.

* Features

- Inherits all [[https://orgmode.org][Org mode features]] (tables, syntax highlighting,
  code blocks evaluation, multiple languages support…)
- Does not require any emacs lisp knowledge
- Does not require any server-side code, nor databases, only a simple
  http server like apache, nginx, lighttpd, hiawatha…
- Allows fine customization of generated html files
- Allows multiple sources for your Org file and let you organize them as
  you wish in the destination folder
- Can use different theme for different sources
- Supports tags and [[https://en.wikipedia.org/wiki/Atom_(Web_standard)][ATOM feeds]]

* How to install it

Neruda is a [[https://rubygems.org/][Ruby gem]]. You need a working Ruby environment to use it. We
recommand you to use [[https://rvm.io][RVM]] and a specific gemset. However it will works
with a global ruby installation too.

#+caption: Installation procedure with RVM
#+begin_src shell
rvm get latest
rvm use ruby-2.6.3@neruda --create
gem install neruda
#+end_src

Now, you're ready to create your first Neruda website.

#+begin_src shell
pablo init -t "My first neruda website"
#+end_src

* Going further

All the Neruda configuration is stored in one [[https://en.wikipedia.org/wiki/YAML][YAML]] file named
~config.yml~ and stored at the root of your project. If none exists, a
default one will be created the first time you run any ~pablo~ command.

You should read the [[./CONFIG.org][config file documentation]] to discover its various
options.
