# frozen_string_literal: true

require 'fronde/config'
require 'r18n-core'

fronde_spec = Gem::Specification.find_by_name 'fronde'
R18n.default_places = "#{fronde_spec.gem_dir}/locales"
R18n.set(Fronde::CONFIG.get('lang', 'en'))
R18n::Filters.on(:named_variables)

Dir.glob("#{fronde_spec.gem_dir}/lib/tasks/*.rake").each { |r| import r }

task default: 'site:build'
